---
title: Jalpc
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Jack's blog,use Jekyll and github pages.
keywords: Jack,Jalpc,blog,Jekyll,github,gh-pages
baseurl: "/ciptamedia"
url: https://riosatria.github.io
author:
  name: Jack
  first_name: Jia
  last_name: Kun
  email: me@jack003.com
  facebook_username: jiakunnj
  github_username: Jack614
  head_img: static/img/landing/Jack.jpg
  desc: I am a Full Stack engineer with website development, automation Ops and writing
    scripts experience. Life is a continuous learning process, so work makes me more
    rigorous, travel makes my life more colorful. I can make lots of friends when
    I coding and travel.
sections:
- id: about-me
  i18n: nav.about_me
  name: About
  tpl: about.html
  css: ''
- id: career
  i18n: nav.career
  name: Career
  tpl: career.html
  css: timeline
- id: skills
  i18n: nav.skills
  name: Skills
  tpl: skills.html
  css: team
- id: projects
  i18n: nav.projects
  name: Projects
  tpl: projects.html
  css: project
- id: blog
  i18n: nav.blog
  name: Blog
  tpl: blog.html
  css: testimonials navy-section
- id: links
  i18n: nav.link
  name: Links
  tpl: links.html
  css: contact
languages:
- locale: en
  flag: static/img/flags/United-States.png
- locale: zh
  flag: static/img/flags/China.png
img_path: http://www.jack003.com/static/img/blog
donate:
  wechat: static/img/pay/wechat.png
  alipay: static/img/pay/alipay.png
changyan: 
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75
ba: 
ga:
  id: UA-73784599-1
gio:
  id: a49d4901c7853da9
encoding: utf-8
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
