# Welcome to Jekyll!

# Website settings
title: "Cipta Media Seluler"
description: "Arsip Cipta Media Seluler,menggunakan Jekyll dan github pages."
keywords: "Cipta Media Seluler,CMS,blog,arsip,Jekyll,github,gh-pages"
baseurl: "/"
url: ""
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Cipta Media Seluler'
  desc: 'Media interaksi dan pembelajaran bersama tentang pemanfaatan teknologi seluler untuk perubahan sosial.'
  head_img: 'static/img/landing/Peningkatan_cipta_media.png'

# sections
sections:
  - id: 'tentang'
    i18n: 'nav.tentang'
    name: 'Tentang'
    tpl: 'tentang.html'
    css: ''

  - id: 'proyek'
    i18n: 'nav.proyek'
    name: 'Proyek Lama'
    tpl: 'proyek.html'
    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: ''

# comment
disqus:
  name: nama_disini
  public_key: public_key_disini

# google analytics
ga:
  id: ga_disini

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
